CMS.API/CMS.API/Controllers/ConferenceController.cs
using CMS.API.BLL.BLL;
using CMS.API.BLL.Interfaces;
using CMS.API.Helpers;
using CMS.BE.DTO;
using CMS.BE.Models;
using System;
using System.Web.Http;

namespace CMS.API.Controllers
{
    [BasicAuthentication]
    public class ConferenceController : ApiController
    {
        private IConferenceBLL _bll = new ConferenceBLL();

        // GET: api/Conference/Conferences
        [HttpGet]
        [Route("api/conference/conferences")]
        public IHttpActionResult GetConferences()
        {
            return Ok(_bll.GetConferences());
        }

        // GET: api/Conference/ConferenceById?conferenceId=
        [HttpGet]
        [Route("api/conference/conferencebyid")]
        public IHttpActionResult GetConferences(int conferenceId)
        {
            var conference = _bll.GetConferenceById(conferenceId);
            if (conference == null) return BadRequest();
            return Ok(conference);
        }

        // POST: api/Conference/AddConference
        [HttpPost]
        [Route("api/conference/addconference")]
        public IHttpActionResult AddConference([FromBody] ConferenceDTO conference)
        {
            if (string.IsNullOrEmpty(conference.Title) || string.IsNullOrEmpty(conference.Place)
                || conference.BeginDate== default(DateTime) || conference.EndDate == default(DateTime)) return BadRequest();
            if (_bll.AddConference(conference)) return Ok();
            return InternalServerError();
        }

        // PUT: api/Conference/EditConference
        [HttpPut]
        [Route("api/conference/editconference")]
        public IHttpActionResult EditConference([FromBody] ConferenceDTO conference)
        {
            if (string.IsNullOrEmpty(conference.Title) || string.IsNullOrEmpty(conference.Place)
                || conference.BeginDate == default(DateTime) || conference.EndDate == default(DateTime)) return BadRequest();
            if (_bll.EditConference(conference)) return Ok();
            return InternalServerError();
        }

        // DELETE: api/Conference/DeleteConference?conferenceId=
        [HttpDelete]
        [Route("api/conference/deleteconference")]
        public IHttpActionResult DeleteConference(int conferenceId)
        {
            if (_bll.DeleteConference(conferenceId)) return Ok();
            return InternalServerError();
        }

        // GET: api/Conference/Program
        [HttpGet]
        [Route("api/conference/program")]
        public IHttpActionResult GetConferenceProgram(int conferenceId)
        {
            try
            {
                var model = _bll.GetConferenceProgram(conferenceId);
                PdfController controller = PdfHelper.Setup("GetProgram");
                return Ok(new ByteArray() { Content = controller.GetProgram(model) });
            }
            catch
            {
                return InternalServerError();
            }
        }

        // GET: api/Conference/Schedule
        [HttpGet]
        [Route("api/conference/schedule")]
        public IHttpActionResult GetConferenceSchedule(int accountId, int conferenceId)
        {
            try
            {
                var model = _bll.GetConferenceSchedule(accountId, conferenceId);
                PdfController controller = PdfHelper.Setup("GetSchedule");
                return Ok(new ByteArray() { Content = controller.GetSchedule(model) });
            }
            catch
            {
                return InternalServerError();
            }
        }

        // GET: api/Conference/ScheduleICal
        [HttpGet]
        [Route("api/conference/scheduleical")]
        public IHttpActionResult GetConferenceScheduleICal(int accountId, int conferenceId)
        {
            try
            {
                var schedule = _bll.GetConferenceScheduleICal(accountId, conferenceId);
                return Ok(new ByteArray() { Content = schedule });
            }
            catch
            {
                return InternalServerError();
            }
        }
    }
}

CMS.API/CMS.API/Controllers/WebController.cs
using CMS.API.BLL.BLL;
using CMS.API.BLL.Interfaces;
using CMS.BE.Models.Program;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMS.API.Controllers
{
    public class WebController : Controller
    {
        private IConferenceBLL _bll = new ConferenceBLL();
        public ActionResult ConferenceProgram(int? id)
        {
            if (!id.HasValue)
            {
                return NotFound();
            }

            var model = _bll.GetConferenceProgram(id.Value);

            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        public ActionResult NotFound()
        {
            return View("NotFound");
        }

        public ActionResult Conferences()
        {
            var conferences = _bll.GetConferences();
            var model = new ConferencesModel()
            {
                Conferences = new List<BE.DTO.ConferenceDTO>()
            };
            if (conferences != null) model.Conferences = conferences.ToList(); 

            return View(model);
        }
    }
}

CMS.API/CMS.API/Views/Web/ConferenceProgram.cshtml
@model CMS.BE.Models.Program.ConferenceProgramModel

@{
    ViewBag.Title = Model.Conference.Title;
}

<h2>@Model.Conference.Title</h2>
<h3>@Model.Conference.Place</h3>
<h3>@Model.Conference.Description</h3>
<h3>@Model.Conference.BeginDate.ToShortDateString() - @Model.Conference.EndDate.ToShortDateString()</h3>
<br />
<h2>Program:</h2>
<div>
    <p>Legend:</p>
    <span style="color:#0000FF">Events &nbsp;&nbsp;</span>
    <span>Sessions &nbsp;&nbsp;</span>
    <span style="font-weight: bold">Special sessions</span>
</div>
<br />
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Title </th>
        <th>Begin Date </th>
        <th>End Date</th>
    </tr>
    @foreach (var m in Model.Entries)
    {
        var color = m.GetType() == typeof(CMS.BE.DTO.EventDTO) ? "#0000FF" : "#000000";
        var weigh = m.GetType() == typeof(CMS.BE.DTO.SpecialSessionDTO) ? "bold" : "normal";
        <tr style="color:@color; font-weight: @weigh">
            <td>@m.Title</td>
            <td>@m.BeginDate</td>
            <td>@m.EndDate</td>
        </tr>
    }
</table>
<br />
<h3>Events:</h3>
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Title </th>
        <th>Begin Date </th>
        <th>End Date</th>
        <th>Description</th>
        <th>Building</th>
        <th>Room</th>
    </tr>
    @foreach (var m in Model.Events)
    {
        <tr>
            <td style="max-width:170px; word-wrap: break-word">@m.Title</td>
            <td>@m.BeginDate</td>
            <td>@m.EndDate</td>
            <td style="max-width:150px; word-wrap: break-word">@m.Description</td>
            <td style="max-width:150px; word-wrap: break-word">@m.BuildingName</td>
            <td>@m.RoomCode</td>
        </tr>
    }
</table>
<br />
<h3>Sessions:</h3>
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Title </th>
        <th>Begin Date </th>
        <th>End Date</th>
        <th>Description</th>
        <th>Building</th>
        <th>Room</th>
        <th>Chairman</th>
    </tr>
    @foreach (var m in Model.Sessions)
    {
        <tr>
            <td style="max-width:170px; word-wrap: break-word">@m.Title</td>
            <td>@m.BeginDate</td>
            <td>@m.EndDate</td>
            <td style="max-width:150px; word-wrap: break-word">@m.Description</td>
            <td style="max-width:150px; word-wrap: break-word">@m.BuildingName</td>
            <td>@m.RoomCode</td>
            <td>@m.AccountName</td>
        </tr>
    }
</table>
<br />
<h3>Special Sessions:</h3>
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Title </th>
        <th>Begin Date </th>
        <th>End Date</th>
        <th>Description</th>
        <th>Building</th>
        <th>Room</th>
        <th>Chairman</th>
    </tr>
    @foreach (var m in Model.SpecialSessions)
    {
        <tr>
            <td style="max-width:170px; word-wrap: break-word">@m.Title</td>
            <td>@m.BeginDate</td>
            <td>@m.EndDate</td>
            <td style="max-width:150px; word-wrap: break-word">@m.Description</td>
            <td style="max-width:150px; word-wrap: break-word">@m.BuildingName</td>
            <td>@m.RoomCode</td>
            <td>@m.AccountName</td>
        </tr>
    }
</table>

CMS.API/CMS.API/Views/Web/Conferences.cshtml
@model CMS.BE.Models.Program.ConferencesModel

@{
    ViewBag.Title = "Conferences";
}

<div>
    <img style="float:left" ; src="/Assets/CMSLogo.png" alt="Logo" />
    <div style="float:left; padding-top:13px" ;>
        <h4 style="font-weight:bold">Conference</h4>
        <h4 style="font-weight:bold">Managment</h4>
        <h4 style="font-weight:bold">System</h4>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<h2>Conferences</h2>
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>Id </th>
        <th>Conference </th>
        <th>Visit</th>
    </tr>
    @foreach (var m in Model.Conferences)
    {
        <tr>
            <td>@m.ConferenceId</td>
            <td>@m.ConferenceDesc</td>
            <td>
                <a href="@Url.Action("ConferenceProgram", "Web", new { id = m.ConferenceId})">
                    Details
                </a>
            </td>
        </tr>
    }
</table>